adminUser:
  password: local:cluster-1/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: billyy@gmail.com
  token: local:cluster-1/pipelineUser:token
  username: billyy
prow:
  hmacToken: local:cluster-1/prow:hmacToken
